### ISSUE TITLE
`Async::Cable` gem name.

### ISSUE THREAD

**Issue by ioquatix** [senid231/async_cable#2]
Hello @senid231,

I'm unable to release a gem called `async-cable` since this gem is released as `async_cable`.

> There was a problem saving your gem: Name ‘async-cable’ is too similar to an existing gem named ‘async_cable’

Are you okay if I release a gem with the name `async-cable`? If so, I believe RubyGems admins can make an exception.

Thanks.

**Comment by senid231** [comment]
Hi, sure. This gem was just an experiment and I don't think anybody using it

**Comment by ioquatix** [comment]
@senid231 thanks for your experiment. I appreciate everyone who has a go at `async` and making things work better.
